import mongoose from "mongoose";
import Property from "./models/Property.js";
import { Agent } from "./models/Agent.js";
mongoose
  .connect("mongodb://127.0.0.1:27017/realestate")
  .then(() => console.log("MongoDB Connected for Seeding..."))
  .catch((err) => console.log("DB Connection Error:", err.message));

const allProperties = [
  {
    title: "The Solstice Oceanfront Modern Villa",
    price: 8450000,
    currency: "$",
    priceType: "",
    badge: "For Sale",
    category: "Villa",
    location: "Malibu Beach, California, USA",
    image:
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
    beds: 6,
    baths: 7,
    area: "8,200 Sq.Ft",
    isFeatured: true,
    view: "Panoramic Ocean View",
    garages: 2,
    lotArea: "0.35 Acres",
    yearBuilt: 2022,
  },
  {
    title: "Aura Minimalist Glass Estate",
    price: 6850000,
    currency: "$",
    priceType: "",
    badge: "For Sale",
    category: "Villa",
    location: "Beverly Hills, Los Angeles, USA",
    image:
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    beds: 5,
    baths: 6,
    area: "6,800 Sq.Ft",
    isFeatured: true,
    view: "City Skyline View",
    garages: 3,
    lotArea: "0.40 Acres",
    yearBuilt: 2023,
  },
  {
    title: "Lumière Palm Island Luxury Resort Villa",
    price: 12500000,
    currency: "$",
    priceType: "",
    badge: "For Sale",
    category: "Villa",
    location: "Palm Jumeirah, Dubai, UAE",
    image:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    beds: 7,
    baths: 8,
    area: "10,500 Sq.Ft",
    isFeatured: true,
    view: "Private Beach & Gulf View",
    garages: 4,
    lotArea: "0.65 Acres",
    yearBuilt: 2024,
  },
  {
    title: "Serenity Palms Waterfront Estate",
    price: 18500,
    currency: "$",
    priceType: "/ month",
    badge: "For Rent",
    category: "Villa",
    location: "Miami Beach, Florida, USA",
    image:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    beds: 4,
    baths: 5,
    area: "5,500 Sq.Ft",
    isFeatured: true,
    view: "Bay Waterfront View",
    garages: 2,
    lotArea: "0.28 Acres",
    yearBuilt: 2021,
  },
  {
    title: "The Horizon Modern Hillside Villa",
    price: 5150000,
    currency: "$",
    priceType: "",
    badge: "For Sale",
    category: "Villa",
    location: "Hollywood Hills, California, USA",
    image:
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80",
    beds: 4,
    baths: 4,
    area: "5,100 Sq.Ft",
    isFeatured: true,
    view: "Canyon & Sunset View",
    garages: 2,
    lotArea: "0.30 Acres",
    yearBuilt: 2020,
  },
  {
    title: "Nirvana Contemporary Coastal Mansion",
    price: 9900000,
    currency: "$",
    priceType: "",
    badge: "For Sale",
    category: "Villa",
    location: "Mayfair, London, UK",
    image:
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    beds: 6,
    baths: 6,
    area: "7,900 Sq.Ft",
    isFeatured: true,
    view: "Private Courtyard View",
    garages: 2,
    lotArea: "0.22 Acres",
    yearBuilt: 2019,
  },
  {
    title: "Verdant Canopy French Riviera Villa",
    price: 22000,
    currency: "$",
    priceType: "/ month",
    badge: "For Rent",
    category: "Villa",
    location: "Côte d'Azur, Nice, France",
    image:
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
    beds: 5,
    baths: 5,
    area: "6,200 Sq.Ft",
    isFeatured: true,
    view: "Mediterranean Sea View",
    garages: 3,
    lotArea: "0.50 Acres",
    yearBuilt: 2022,
  },
  {
    title: "The Palm Residency High-Rise Suite",
    price: 3200000,
    currency: "$",
    priceType: "",
    badge: "For Sale",
    category: "Apartment",
    location: "Downtown, Los Angeles, USA",
    image:
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
    beds: 3,
    baths: 3,
    area: "3,100 Sq.Ft",
    isFeatured: true,
    view: "Downtown Skyline",
    garages: 2,
    lotArea: "N/A (Apartment)",
    yearBuilt: 2023,
  },
  {
    title: "Skyline Royal Glass Penthouse",
    price: 5400000,
    currency: "$",
    priceType: "",
    badge: "For Sale",
    category: "Apartment",
    location: "Manhattan, New York, USA",
    image:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    beds: 4,
    baths: 4,
    area: "4,500 Sq.Ft",
    isFeatured: true,
    view: "Central Park & Cityscape",
    garages: 2,
    lotArea: "N/A (Penthouse)",
    yearBuilt: 2024,
  },
  {
    title: "Glass Tower Executive Studio & Suite",
    price: 8500,
    currency: "$",
    priceType: "/ month",
    badge: "For Rent",
    category: "Apartment",
    location: "Marina Bay, Singapore",
    image:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
    beds: 2,
    baths: 2,
    area: "1,800 Sq.Ft",
    isFeatured: true,
    view: "Marina Bay Sands View",
    garages: 1,
    lotArea: "N/A (Studio)",
    yearBuilt: 2022,
  },
  {
    title: "Botanica Green Modern Apartments",
    price: 2100000,
    currency: "$",
    priceType: "",
    badge: "For Sale",
    category: "Apartment",
    location: "Canary Wharf, London, UK",
    image:
      "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80",
    beds: 3,
    baths: 2,
    area: "2,400 Sq.Ft",
    isFeatured: true,
    view: "River Thames View",
    garages: 1,
    lotArea: "N/A (Apartment)",
    yearBuilt: 2021,
  },
  {
    title: "The Bronze Heights City View Suite",
    price: 6200,
    currency: "$",
    priceType: "/ month",
    badge: "For Rent",
    category: "Apartment",
    location: "Shinjuku, Tokyo, Japan",
    image:
      "https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&w=1200&q=80",
    beds: 2,
    baths: 2,
    area: "1,950 Sq.Ft",
    isFeatured: true,
    view: "Tokyo Tower / City Lights",
    garages: 1,
    lotArea: "N/A (Suite)",
    yearBuilt: 2023,
  },
  {
    title: "Mountain Ridge Luxury Row Townhouse",
    price: 3800000,
    currency: "$",
    priceType: "",
    badge: "For Sale",
    category: "Townhouse",
    location: "Aspen, Colorado, USA",
    image:
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80",
    beds: 4,
    baths: 4,
    area: "3,800 Sq.Ft",
    isFeatured: true,
    view: "Snow Mountain Valley",
    garages: 2,
    lotArea: "0.15 Acres",
    yearBuilt: 2021,
  },
  {
    title: "Classic Suburban Family Townhouse",
    price: 2950000,
    currency: "$",
    priceType: "",
    badge: "For Sale",
    category: "Townhouse",
    location: "Kensington, London, UK",
    image:
      "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80",
    beds: 4,
    baths: 3,
    area: "3,200 Sq.Ft",
    isFeatured: true,
    view: "Garden / Tree-lined Street",
    garages: 1,
    lotArea: "0.12 Acres",
    yearBuilt: 2020,
  },
  {
    title: "The Heritage Dual-Door Modern Townhouse",
    price: 7500,
    currency: "$",
    priceType: "/ month",
    badge: "For Rent",
    category: "Townhouse",
    location: "Amsterdam Canal Belt, Netherlands",
    image:
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    beds: 3,
    baths: 3,
    area: "2,900 Sq.Ft",
    isFeatured: true,
    view: "Canal Waterfront View",
    garages: 1,
    lotArea: "0.10 Acres",
    yearBuilt: 2018,
  },
  {
    title: "Metropolitan Urban Row Home",
    price: 2450000,
    currency: "$",
    priceType: "",
    badge: "For Sale",
    category: "Townhouse",
    location: "San Francisco, California, USA",
    image:
      "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&w=1200&q=80",
    beds: 3,
    baths: 3,
    area: "2,650 Sq.Ft",
    isFeatured: true,
    view: "Bay & Urban Street",
    garages: 2,
    lotArea: "0.08 Acres",
    yearBuilt: 2022,
  },
  {
    title: "Greenway Newly Developed Modern Row Townhouse",
    price: 5800,
    currency: "$",
    priceType: "/ month",
    badge: "For Rent",
    category: "Townhouse",
    location: "Melbourne Suburban Arc, Australia",
    image:
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
    beds: 3,
    baths: 2,
    area: "2,500 Sq.Ft",
    isFeatured: true,
    view: "Parklands & Green Belt",
    garages: 2,
    lotArea: "0.14 Acres",
    yearBuilt: 2023,
  },
];
const sampleGallery = [
  "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=800&q=80",
];

const seedDB = async () => {
  try {
    const anyAgent = await Agent.findOne();

    const enrichedProperties = allProperties.map((item, index) => ({
      ...item,
      propertyId: `NV-${12458 + index}`,
      images: [item.image, ...sampleGallery],
      description: `Experience the perfect blend of modern luxury and oceanfront living at ${item.title}.\n\nThis stunning ${item.beds}-bedroom ${item.category.toLowerCase()} offers breathtaking views, premium amenities, and superior craftsmanship throughout.\n\nEnjoy expansive living spaces, a state-of-the-art kitchen, infinity pool, private beach access, and smart home technology.`,
      features: [
        "Expansive open-concept living and dining areas",
        "Floor-to-ceiling windows with stunning views",
        "Infinity pool, spa, and outdoor kitchen",
        "Private beach access and landscaped gardens",
        "Smart home system with advanced security",
      ],
      amenities: [
        "Infinity Pool",
        "Private Beach",
        "Home Theater",
        "Smart Home",
        "Fireplace",
        "Outdoor Kitchen",
        "Gym",
        "Spa",
        "Wine Cellar",
        "Elevator",
        "Security System",
        "Landscaped Garden",
      ],
      floors:
        item.category === "Villa" ? 3 : item.category === "Townhouse" ? 2 : 1,
      furnished: "Fully Furnished",
      agent: anyAgent ? anyAgent._id : undefined,
    }));

    await Property.deleteMany({});
    await Property.insertMany(enrichedProperties);
    console.log(
      "Database Seeded Successfully with complete descriptions & details! 🌎✨",
    );
  } catch (error) {
    console.error("Error Seeding Database:", error);
  } finally {
    mongoose.connection.close();
  }
};

seedDB();
