import mongoose from "mongoose";
import dotenv from "dotenv";
import { Agent } from "./models/Agent.js";

dotenv.config();

const agentsData = [
  {
    name: "Michael Anderson",
    role: "CEO & Founder",
    badge: "Top Rated",
    badgeTagline: "Among top 1% agents on NestVault",
    isVerified: true,
    image:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviewsCount: 128,
    bio: "With over 12 years of experience in luxury real estate, Michael specializes in high-end residential and investment properties.",
    experienceYears: 12,
    propertiesSold: 248,
    totalSales: "$320M+",
    clientSatisfaction: "98%",
    email: "michael.anderson@nestvault.com",
    phone: "+1 (123) 456-7890",
    location: "California",
    languages: ["English", "Spanish"],
    socials: {
      linkedin: "https://linkedin.com",
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
    },
    aboutText:
      "Michael Anderson is the founder and lead real estate expert at NestVault Real Estate. His deep market knowledge and negotiation skills have made him a top name in luxury housing.",
    certifications: [
      "Certified Luxury Home Marketing Specialist (CLHMS)",
      "Accredited Buyer's Representative (ABR)",
      "Certified Residential Specialist (CRS)",
    ],
    areasOfExpertise: [
      "Luxury Homes",
      "Investments",
      "Villas",
      "New Construction",
      "Relocation",
    ],
  },
  {
    name: "Sophia Martinez",
    role: "Senior Property Consultant",
    badge: "Top Rated",
    badgeTagline: "Top performer in residential estates",
    isVerified: true,
    image:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewsCount: 96,
    bio: "Specializing in family homes and modern apartments with a focus on seamless client experience.",
    experienceYears: 8,
    propertiesSold: 186,
    totalSales: "$180M+",
    clientSatisfaction: "97%",
    email: "sophia.martinez@nestvault.com",
    phone: "+1 (123) 456-7891",
    location: "California",
    languages: ["English", "Spanish", "French"],
    socials: {
      linkedin: "https://linkedin.com",
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
    },
    aboutText:
      "Sophia has spent nearly a decade guiding families to find their dream homes across California's prime locations.",
    certifications: [
      "Certified Residential Specialist (CRS)",
      "Real Estate Negotiation Expert (RENE)",
    ],
    areasOfExpertise: ["Residential Homes", "Apartments", "First-Time Buyers"],
  },
  {
    name: "David Thompson",
    role: "Head of Sales",
    badge: "Top Rated",
    badgeTagline: "Leading commercial & luxury sales",
    isVerified: true,
    image:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviewsCount: 104,
    bio: "Expert in commercial acquisitions and investment portfolios across major US markets.",
    experienceYears: 10,
    propertiesSold: 215,
    totalSales: "$250M+",
    clientSatisfaction: "99%",
    email: "david.thompson@nestvault.com",
    phone: "+1 (123) 456-7892",
    location: "New York",
    languages: ["English"],
    socials: {
      linkedin: "https://linkedin.com",
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
    },
    aboutText:
      "David heads our sales operations in New York, specializing in high-value commercial properties and penthouses.",
    certifications: [
      "Certified Commercial Investment Member (CCIM)",
      "Sellers Representative Specialist (SRS)",
    ],
    areasOfExpertise: [
      "Commercial Property",
      "Penthouses",
      "Investment Strategy",
    ],
  },
  {
    name: "Emily Johnson",
    role: "Marketing Director & Advisor",
    badge: "Top Rated",
    badgeTagline: "Luxury marketing and estate strategist",
    isVerified: true,
    image:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewsCount: 72,
    bio: "Combines cutting-edge digital marketing strategies with real estate consulting to maximize property values.",
    experienceYears: 7,
    propertiesSold: 142,
    totalSales: "$140M+",
    clientSatisfaction: "96%",
    email: "emily.johnson@nestvault.com",
    phone: "+1 (123) 456-7893",
    location: "Florida",
    languages: ["English"],
    socials: {
      linkedin: "https://linkedin.com",
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
    },
    aboutText:
      "Emily connects buyers with premier waterfront properties across Miami using targeted modern marketing.",
    certifications: [
      "Digital Marketing Specialist",
      "Accredited Buyer's Representative",
    ],
    areasOfExpertise: ["Waterfront Estates", "Beach Houses", "Luxury Condos"],
  },
  {
    name: "Daniel Roberts",
    role: "Property Consultant",
    badge: "Verified",
    badgeTagline: "Commercial & retail property advisor",
    isVerified: true,
    image:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewsCount: 88,
    bio: "Dedicated to helping businesses locate optimal office and retail spaces in thriving commercial hubs.",
    experienceYears: 6,
    propertiesSold: 128,
    totalSales: "$110M+",
    clientSatisfaction: "95%",
    email: "daniel.roberts@nestvault.com",
    phone: "+1 (123) 456-7894",
    location: "New York",
    languages: ["English", "German"],
    socials: {
      linkedin: "https://linkedin.com",
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
    },
    aboutText:
      "Daniel has built a reputation for quick execution and solid deal structuring in commercial business districts.",
    certifications: ["Commercial Property Specialist (CPS)"],
    areasOfExpertise: [
      "Office Spaces",
      "Retail Properties",
      "Commercial Leases",
    ],
  },
  {
    name: "Olivia Brown",
    role: "Senior Property Advisor",
    badge: "Verified",
    badgeTagline: "Residential specialist in suburban luxury",
    isVerified: true,
    image:
      "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviewsCount: 53,
    bio: "Helps clients discover tranquil suburban villas and eco-friendly smart homes.",
    experienceYears: 9,
    propertiesSold: 175,
    totalSales: "$195M+",
    clientSatisfaction: "98%",
    email: "olivia.brown@nestvault.com",
    phone: "+1 (123) 456-7895",
    location: "California",
    languages: ["English", "Italian"],
    socials: {
      linkedin: "https://linkedin.com",
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
    },
    aboutText:
      "Olivia advocates sustainable living, specializing in modern smart homes and suburban family compounds.",
    certifications: [
      "Green Designation (GREEN)",
      "Certified Residential Specialist",
    ],
    areasOfExpertise: ["Suburban Villas", "Smart Homes", "Eco-Estates"],
  },
  {
    name: "James Wilson",
    role: "Property Investment Advisor",
    badge: "Featured",
    badgeTagline: "High-yield investment property expert",
    isVerified: true,
    image:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewsCount: 67,
    bio: "Guiding international and local investors to build high-ROI real estate portfolios.",
    experienceYears: 8,
    propertiesSold: 133,
    totalSales: "$160M+",
    clientSatisfaction: "96%",
    email: "james.wilson@nestvault.com",
    phone: "+1 (123) 456-7896",
    location: "Florida",
    languages: ["English"],
    socials: {
      linkedin: "https://linkedin.com",
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
    },
    aboutText:
      "James analyzes market trends to recommend properties with high rental yields and capital appreciation.",
    certifications: ["Certified Real Estate Investment Specialist"],
    areasOfExpertise: [
      "Investment Properties",
      "Rental Hubs",
      "Land Development",
    ],
  },
  {
    name: "Ava Taylor",
    role: "Property Consultant",
    badge: "Featured",
    badgeTagline: "Urban penthouse specialist",
    isVerified: true,
    image:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewsCount: 49,
    bio: "Passion for urban high-rise apartments, luxury penthouses, and modern architectural spaces.",
    experienceYears: 5,
    propertiesSold: 96,
    totalSales: "$90M+",
    clientSatisfaction: "97%",
    email: "ava.taylor@nestvault.com",
    phone: "+1 (123) 456-7897",
    location: "California",
    languages: ["English", "French"],
    socials: {
      linkedin: "https://linkedin.com",
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
    },
    aboutText:
      "Ava specializes in luxury high-rises and modern townhouses across San Francisco and Los Angeles.",
    certifications: ["Luxury Home Specialist"],
    areasOfExpertise: ["Penthouses", "High-Rise Apartments", "Townhouses"],
  },
  {
    name: "Ethan Clark",
    role: "Senior Agent & Valuation Expert",
    badge: "Top Rated",
    badgeTagline: "Accurate valuation and sales specialist",
    isVerified: true,
    image:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviewsCount: 112,
    bio: "Over a decade of experience evaluating prestige properties and negotiating complex residential deals.",
    experienceYears: 11,
    propertiesSold: 230,
    totalSales: "$280M+",
    clientSatisfaction: "98%",
    email: "ethan.clark@nestvault.com",
    phone: "+1 (123) 456-7898",
    location: "New York",
    languages: ["English"],
    socials: {
      linkedin: "https://linkedin.com",
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
    },
    aboutText:
      "Ethan brings deep mathematical analysis and price precision to sellers looking for top dollar.",
    certifications: ["Certified Residential Appraiser", "SRS"],
    areasOfExpertise: ["Property Valuation", "Luxury Sales", "Estate Deals"],
  },
  {
    name: "Chloe Davis",
    role: "Luxury Estate Specialist",
    badge: "Verified",
    badgeTagline: "Specialist in private mansions",
    isVerified: true,
    image:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewsCount: 61,
    bio: "Curating confidential deals for high-net-worth individuals seeking private mansions and private islands.",
    experienceYears: 7,
    propertiesSold: 105,
    totalSales: "$210M+",
    clientSatisfaction: "99%",
    email: "chloe.davis@nestvault.com",
    phone: "+1 (123) 456-7899",
    location: "Florida",
    languages: ["English", "Spanish"],
    socials: {
      linkedin: "https://linkedin.com",
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
    },
    aboutText:
      "Chloe caters to high-profile clients looking for complete privacy and exclusive architectural masterpieces.",
    certifications: ["CLHMS - Guild Member"],
    areasOfExpertise: ["Mansions", "Private Estates", "Waterfront Properties"],
  },
  {
    name: "Lucas Miller",
    role: "Commercial Acquisition Specialist",
    badge: "Top Rated",
    badgeTagline: "Leading multi-family and industrial deals",
    isVerified: true,
    image:
      "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviewsCount: 85,
    bio: "Specializes in multi-family apartment complexes and industrial warehouse logistics parks.",
    experienceYears: 10,
    propertiesSold: 160,
    totalSales: "$310M+",
    clientSatisfaction: "96%",
    email: "lucas.miller@nestvault.com",
    phone: "+1 (123) 456-7900",
    location: "Chicago",
    languages: ["English"],
    socials: {
      linkedin: "https://linkedin.com",
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
    },
    aboutText:
      "Lucas manages institutional investors and real estate funds expanding their physical footprint.",
    certifications: ["CCIM Designation"],
    areasOfExpertise: [
      "Multi-Family Housing",
      "Industrial Warehouses",
      "Commercial Land",
    ],
  },
  {
    name: "Mia White",
    role: "Relocation & Housing Specialist",
    badge: "Verified",
    badgeTagline: "Corporate and executive relocation",
    isVerified: true,
    image:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewsCount: 43,
    bio: "Helping executives and families smoothly transition between cities with hassle-free home finding.",
    experienceYears: 4,
    propertiesSold: 78,
    totalSales: "$75M+",
    clientSatisfaction: "98%",
    email: "mia.white@nestvault.com",
    phone: "+1 (123) 456-7901",
    location: "California",
    languages: ["English", "Mandarin"],
    socials: {
      linkedin: "https://linkedin.com",
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
    },
    aboutText:
      "Mia works directly with corporate HR departments to place incoming executives into luxury homes.",
    certifications: ["Certified Relocation Professional (CRP)"],
    areasOfExpertise: [
      "Executive Rentals",
      "Corporate Relocation",
      "Luxury Condos",
    ],
  },
  {
    name: "Noah Harris",
    role: "Property Advisor",
    badge: "Featured",
    badgeTagline: "New construction & development specialist",
    isVerified: true,
    image:
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewsCount: 58,
    bio: "Partners with top builders and developers to offer clients exclusive pre-construction prices.",
    experienceYears: 6,
    propertiesSold: 115,
    totalSales: "$135M+",
    clientSatisfaction: "95%",
    email: "noah.harris@nestvault.com",
    phone: "+1 (123) 456-7902",
    location: "Florida",
    languages: ["English"],
    socials: {
      linkedin: "https://linkedin.com",
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
    },
    aboutText:
      "Noah helps buyers purchase off-plan properties before public launches to lock in early equity.",
    certifications: ["New Home Construction Specialist"],
    areasOfExpertise: [
      "New Construction",
      "Off-Plan Projects",
      "Architectural Villas",
    ],
  },
  {
    name: "Isabella King",
    role: "Senior Property Consultant",
    badge: "Top Rated",
    badgeTagline: "Historic and heritage homes expert",
    isVerified: true,
    image:
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviewsCount: 91,
    bio: "Passionate about preserving historic architecture while matching buyers with classic mansions.",
    experienceYears: 10,
    propertiesSold: 152,
    totalSales: "$220M+",
    clientSatisfaction: "99%",
    email: "isabella.king@nestvault.com",
    phone: "+1 (123) 456-7903",
    location: "New York",
    languages: ["English", "Spanish"],
    socials: {
      linkedin: "https://linkedin.com",
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
    },
    aboutText:
      "Isabella is renowned for her knowledge of vintage architecture, brownstones, and restored classic homes.",
    certifications: ["Historic Property Specialist"],
    areasOfExpertise: ["Brownstones", "Heritage Homes", "Classic Mansions"],
  },
  {
    name: "Benjamin Scott",
    role: "Residential Property Expert",
    badge: "Verified",
    badgeTagline: "Suburban family community specialist",
    isVerified: true,
    image:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewsCount: 64,
    bio: "Helping growing families find spacious suburban houses near top-ranked school districts.",
    experienceYears: 7,
    propertiesSold: 140,
    totalSales: "$125M+",
    clientSatisfaction: "96%",
    email: "benjamin.scott@nestvault.com",
    phone: "+1 (123) 456-7904",
    location: "Chicago",
    languages: ["English"],
    socials: {
      linkedin: "https://linkedin.com",
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
    },
    aboutText:
      "Benjamin prioritizes family lifestyle needs, matching parents with neighborhood communities.",
    certifications: ["Accredited Buyer's Representative"],
    areasOfExpertise: ["Family Homes", "Suburban Estates", "Gated Communities"],
  },
  {
    name: "Amelia Wright",
    role: "Waterfront Estate Specialist",
    badge: "Featured",
    badgeTagline: "Coastal & island luxury specialist",
    isVerified: true,
    image:
      "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewsCount: 77,
    bio: "Specializes in luxury oceanfront properties, private docks, and resort-style living.",
    experienceYears: 8,
    propertiesSold: 118,
    totalSales: "$240M+",
    clientSatisfaction: "97%",
    email: "amelia.wright@nestvault.com",
    phone: "+1 (123) 456-7905",
    location: "Florida",
    languages: ["English", "Portuguese"],
    socials: {
      linkedin: "https://linkedin.com",
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
    },
    aboutText:
      "Amelia represents high-value coastal properties, assisting clients looking for dock access and ocean views.",
    certifications: ["Luxury Waterfront Specialist"],
    areasOfExpertise: ["Oceanfront Homes", "Private Docks", "Resort Condos"],
  },
];

const seedAgents = async () => {
  try {
    const connStr =
      process.env.MONGO_URI || "mongodb://127.0.0.1:27017/realestate";
    await mongoose.connect(connStr);
    console.log("Connected to MongoDB (realestate)!");
    await Agent.deleteMany({});
    console.log("Old agents deleted.");
    await Agent.insertMany(agentsData);
    console.log("🔥 Successfully seeded 16 Agents to MongoDB!");

    process.exit(0);
  } catch (error) {
    console.error("Error seeding agents:", error.message);
    process.exit(1);
  }
};

seedAgents();
